export const INVALID_CREDENTIALS_MESSAGE = 'Invalid credentials';

export const LOCKOUT_THRESHOLD = 5;

export const LOCKOUT_DURATION_MS = 15 * 60 * 1000;

export const AUTH_ERROR_CODES = {
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  USER_INACTIVE: 'USER_INACTIVE',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  EMAIL_CONFLICT: 'EMAIL_CONFLICT',
  NOT_FOUND: 'NOT_FOUND',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
} as const;
