export const ACCOUNTS_ERROR_CODES = {
  ACCOUNT_NOT_FOUND: 'ACCOUNT_NOT_FOUND',
  PERSON_NOT_FOUND: 'PERSON_NOT_FOUND',
  ACCOUNT_NAME_TAX_CONFLICT: 'ACCOUNT_NAME_TAX_CONFLICT',
  ACCOUNT_TAX_ID_CONFLICT: 'ACCOUNT_TAX_ID_CONFLICT',
  PERSON_EMAIL_CONFLICT: 'PERSON_EMAIL_CONFLICT',
  ACCOUNT_HAS_PEOPLE: 'ACCOUNT_HAS_PEOPLE',
  PERSON_REFERENCED: 'PERSON_REFERENCED',
  ACCOUNT_ID_REQUIRED: 'ACCOUNT_ID_REQUIRED',
  ACCOUNT_CONFLICT: 'ACCOUNT_CONFLICT',
} as const;
